USE AdventureWorksDW2017;

CREATE SCHEMA BRONZE;
GO

ALTER SCHEMA BRONZE TRANSFER dbo.AdventureWorksDWBuildVersion;
ALTER SCHEMA BRONZE TRANSFER dbo.DatabaseLog;
ALTER SCHEMA BRONZE TRANSFER dbo.DimAccount;
ALTER SCHEMA BRONZE TRANSFER dbo.DimCurrency;
ALTER SCHEMA BRONZE TRANSFER dbo.DimCustomer;
ALTER SCHEMA BRONZE TRANSFER dbo.DimDate;
ALTER SCHEMA BRONZE TRANSFER dbo.DimDepartmentGroup;
ALTER SCHEMA BRONZE TRANSFER dbo.DimEmployee;
ALTER SCHEMA BRONZE TRANSFER dbo.DimGeography;
ALTER SCHEMA BRONZE TRANSFER dbo.DimOrganization;
ALTER SCHEMA BRONZE TRANSFER dbo.DimProduct;
ALTER SCHEMA BRONZE TRANSFER dbo.DimProductCategory;
ALTER SCHEMA BRONZE TRANSFER dbo.DimProductSubcategory;
ALTER SCHEMA BRONZE TRANSFER dbo.DimPromotion;
ALTER SCHEMA BRONZE TRANSFER dbo.DimReseller;
ALTER SCHEMA BRONZE TRANSFER dbo.DimSalesReason;
ALTER SCHEMA BRONZE TRANSFER dbo.DimSalesTerritory;
ALTER SCHEMA BRONZE TRANSFER dbo.DimScenario;
ALTER SCHEMA BRONZE TRANSFER dbo.FactAdditionalInternationalProductDescription;
ALTER SCHEMA BRONZE TRANSFER dbo.FactCallCenter;
ALTER SCHEMA BRONZE TRANSFER dbo.FactCurrencyRate;
ALTER SCHEMA BRONZE TRANSFER dbo.FactFinance;
ALTER SCHEMA BRONZE TRANSFER dbo.FactInternetSales;
ALTER SCHEMA BRONZE TRANSFER dbo.FactInternetSalesReason;
ALTER SCHEMA BRONZE TRANSFER dbo.FactProductInventory;
ALTER SCHEMA BRONZE TRANSFER dbo.FactResellerSales;
ALTER SCHEMA BRONZE TRANSFER dbo.FactSalesQuota;
ALTER SCHEMA BRONZE TRANSFER dbo.FactSurveyResponse;
ALTER SCHEMA BRONZE TRANSFER dbo.NewFactCurrencyRate;
ALTER SCHEMA BRONZE TRANSFER dbo.ProspectiveBuyer;
